config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_fstab:
    src: etc/fstab
    dst: /etc/fstab
  f_bash_history:
    src: bash_history
    dst: ~/.bash_history
    chmod: '600'
profiles:
  probook:
    dotfiles:
    - f_bashrc
    - f_fstab
    - f_bash_history
