config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_fstab:
    src: etc/fstab
    dst: /etc/fstab
  f_bash_history:
    src: bash_history
    dst: ~/.bash_history
    chmod: '600'
  f_applist:
    src: applist
    dst: ~/applist
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  d_i3:
    src: config/i3
    dst: ~/.config/i3
profiles:
  probook:
    dotfiles:
    - f_bashrc
    - f_fstab
    - f_bash_history
    - f_applist
    - f_alacritty.yml
    - d_i3
