config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
profiles:
  probook:
    dotfiles:
    - f_bashrc
